apiVersion: v1
kind: Pod
metadata:
  labels:
    qos.coreweave.cloud/latency: low
  name: guanaco-discord-bot-selenium
  namespace: tenant-chairesearch-test
spec:
  volumes:
    - name: chai-datasets
      persistentVolumeClaim:
        claimName: chai-datasets
  imagePullSecrets:
    - name: docker-creds
  containers:
    - name: discord
      image: gcr.io/chai-959f8/downloader:discord
      imagePullPolicy: Always
      command: [ "sleep" ]
      args: [ "infinity" ]
      resources:
        limits:
          cpu: "20"
          #nvidia.com/gpu: "1"
          memory: 32Gi
        requests:
          cpu: "20"
          memory: 32Gi
      volumeMounts:
        - name: chai-datasets
          mountPath: /mnt
      readinessProbe:
        exec:
          command:
            - cat
            - /tmp/ready
        failureThreshold: 1
        initialDelaySeconds: 10
        periodSeconds: 10
        timeoutSeconds: 5
        successThreshold: 1
